# Configuration for probot-auto-merge - https://github.com/bobvanderlinden/probot-auto-merge

updateBranch: true
deleteBranchAfterMerge: false
reportStatus: true

minApprovals:
  MEMBER: 1
  COLLABORATOR: 0
maxRequestedChanges:
  NONE: 0
  
mergeCommitMessage: |
  {testmerge} (#{13})
  {test the automerge process}

blockingLabels:
- blocked

# Will merge whenever the above conditions are met, but also
# the owner has approved or merge label was added.
rules:
- minApprovals:
    OWNER: 1
- requiredLabels:
  - ReadyForMerge    
